dist: trusty
sudo: false

language: node_js
node_js:
  - "12"

addons:
  chrome: stable

cache:
  directories:
    - ./packages/phoenix-ng/node_modules
    - ./packages/phoenix-event-display/node_modules

install:
  - npm install --global yarn lerna
  - yarn install:dependencies

script:
  - yarn test:coverage
  # Set up surge and deploy for PR
  - if [ "$TRAVIS_PULL_REQUEST" != false ]; then chmod +x ./scripts/pr_deploy.sh; ./scripts/pr_deploy.sh; fi

after_success:
  - cd ./packages/phoenix-ng
  - yarn coveralls
